### ISSUE TITLE
Lygisk installation fails after additional setup required screen

### ISSUE THREAD

**Issue by iLagTooMuch** [programminghoch10/Lygisk#39]
Lygisk installs fine from recovery but then fails when it says "Additional setup required" just saying "Installation failed!" in the verbose console.

Device: Samsung T505
OS: LineageOS 21 official, build 3rd Nov 2024

**Comment by binarynoise** [comment]
fixed by https://github.com/programminghoch10/Lygisk/commit/fa36075c7139db5256adec065122c84743323448

**Comment by iLagTooMuch** [comment]
Works now.

**Comment by panomitrius** [comment]
Does not work for me, I still get Installation failed. 


```
- Target image: /dev/block/by-name/boot
- Device platform: arm64-v8a
- Installing: v28.100 (28100)
- Adding addon.d survival script
mkdir: can't create directory '/system/addon.d/magisk': No space left on device
! Installation failed

```

Device: Samsung S10e
OS: Linageos 21 for MicroG (updated 5th of December 2024)

**Comment by binarynoise** [comment]
That's a lineage for microg issue. The system partition has internationally no space left, because one doesn't need to flash anything because gapps are built-in

**Comment by iLagTooMuch** [comment]
@panomitrius You can use TWRP to expand the system partition by going into wipe then system then resize fs I believe. If you're using Lineage recovery then wait for Lineage 22 because they are revising the system partition size for gapps which will inturn leave more space for Lygisk.

**Comment by Photolunatic** [comment]
Issue persists on March 2025 LineageOS 22.1 (microG) I just installed.

**Comment by panomitrius** [comment]
Any workaround for Linageos 22.1 (microG)?
