### ISSUE TITLE
Requires App re install after OTA

### ISSUE THREAD

**Issue by kennyke16** [programminghoch10/Lygisk#44]
I'm using LOS 22.2, A-only device. After OTA, lygisk asks me to reinstall/update the app. I choose "direct install", then it installs and reboot. I didn't have to do this with the previous version of lygisk.

**Comment by binarynoise** [comment]
I don't know how this slipped through testing, but it should work now.
Through the Lygisk app, install the App again (this will download the new version with the fix), then you'll need one more installation of Lygisk and OTA should work again.

**Comment by Zokii0** [comment]
I'm also using LOS 22.2, but still facing the same issue. I have to reinstall Lygisk every week after LOS security update, that wasn't the case with previous version of Lygisk (version 28 or so). At least don't have to reinstall through fastboot or cable, but inside app says "Requires additional setup".

**Comment by programminghoch10** [comment]
@Zokii0 Please re-download Lygisk from the releases page and install the new APK, then retry if this issue still persists.
We fixed it, but didn't up the version to keep in line with Magisk release cycle.

**Comment by Zokii0** [comment]
> [@Zokii0](https://github.com/Zokii0) Please re-download Lygisk from the releases page and install the new APK, then retry if this issue still persists. We fixed it, but didn't up the version to keep in line with Magisk release cycle.

I'm already using latest version of Lygisk with Obtainium from 3 weeks ago (30.6), so this is my 3rd time having to reinstall app after system update. I saw here before that issue was resolved, so I thought maybe need to try on next system update, but still having that issue.

**Comment by binarynoise** [comment]
You need to re-download even if you have 30.6 installed to get the fix.
We replaced the apk with a fixed version but couldn't increase the version to keep in sync with Magisk.

**Comment by Zokii0** [comment]
Ah my bad, didn't understand that part, but yes I indeed updated app instead of uninstalling previous and redownloading new version, I'll reinstall it completely and see how it acts on next system update, thanks
